### ISSUE TITLE
Add hubot-seen external script

### ISSUE THREAD

**Issue by davehunt** [mozilla/webqabot#19]
It would be handy to see when a user was last active. We should install the external [hubot-seen](https://github.com/hubot-scripts/hubot-seen) script to enable this.

**Comment by MonicaG** [comment]
Going to work on this one.

**Comment by MonicaG** [comment]
Hi @davehunt and @bobsilverberg 

The hubot-seen script has a HUBOT_SEEN_TIMEAGO configuration variable.  If it is not set it will report last seen as:

> shell was last seen in Shell at Wed Feb 03 2016 21:36:33 GMT-0800 (PST)

If it is set, it will report the last seen time as relative:

> shell was last seen in Shell less than a minute ago

Do you have a preference?

**Comment by bobsilverberg** [comment]
Hi @MonicaG, good question!  I think I prefer the latter. What do you think @davehunt?

**Comment by davehunt** [comment]
I also prefer the time since over the absolute time.

**Comment by MonicaG** [comment]
Hi,
Regarding the [app.json](https://github.com/mozilla/webqabot/blob/master/app.json) file, do I need to add the HUBOT_SEEN_TIMEAGO config variable to it? 

I read the https://devcenter.heroku.com/articles/app-json-schema and https://devcenter.heroku.com/articles/setting-up-apps-using-the-heroku-platform-api  pages and it looks like the app.json file is used when setting up an app through the Platform API.  I tried doing that, but the app.json file fails validation because values are not defined for some of the entries (i.e. HUBOT_BUGZILLA_URL)

So, I'm wondering how is the app.json file is used?  Do I need to add the HUBOT_SEEN_TIMEAGO config variable to it?

If I set the HUBOT_SEEN_TIMEAGO  config value through the heroku dashboard then the value is picked up and used as expected. (I set up my fork of webqabot and deployed it to heroku)

Thanks!

**Comment by bobsilverberg** [comment]
@MonicaG we only use the `app.json` file for creating review apps, and it seems to work for that. If this new config variable is required to exist for the app to work then you should add it to `app.json`. We don't use if for the Platform API. We could easily test to see if it's needed if you open a PR, and then I can create a review app for that PR and see if it works. Or you could just add it to be on the safe side. ;)

**Comment by MonicaG** [comment]
I added HUBOT_SEEN_TIMEAGO to the app.json file.  It's not required, as the app will run without it.  However, when that config is set (to any value) then the last seen time will be reported as a relative value vs an absolute value.
